### ISSUE TITLE
Version 0.3.6 is missing

### ISSUE THREAD

**Issue by kelset** [DickyT/react-native-textinput-utils#16]
Hi there,
first off thanks for your lib - I want to add it to my RN 0.38 project, but obviously I can't use the 0.3.7 version.
I tried downgrading to 0.3.6 using `npm install react-native-textinput-utils@0.3.6 --save` but I get back from npm this message:

```
npm ERR! notarget No compatible version found: react-native-textinput-utils@0.3.6
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.3.7, 0.3.0, 0.2.7, 0.2.6, 0.2.5, 0.2.1, 0.2.0, 0.0.8, 0.0.7
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Could it be that you overwrote it when updating to 0.3.7?

(as a temporary workaround I'm using 0.3.0)

**Comment by DickyT** [comment]
What error did u get on your 0.38 project? Actually 0.3.6 is a fake version number, I did a fast-forward upgrade to support RN 0.40, but after pushing to github I realized that something is missing and it will cause the plugin crash, so I make some change and publish 0.3.7 to npm and github.

**Comment by kelset** [comment]
Hey.
I imagine you mean which error I get when I tried building the XCode project using 0.3.7 ;)

Here it is:

`[...]/node_modules/react-native-textinput-utils/RCTTextInputUtils/RCTKeyboardPicker.h:10:9: 'React/RCTBridgeModule.h' file not found`

---

btw 0.3.0 was too old so I couldn't use it either. T_T

**Comment by DickyT** [comment]
It is a header path error. Go to the Xcode project of this plugin, set the header search path to the correct relative path.

**Comment by kelset** [comment]
Actually, I fixed it by changing each header styled like:
`import <React/RCTBridgeModule.h>`
to 
`import "RCTBridgeModule.h"`

But your solution may work too.

**Comment by DickyT** [comment]
Good to see that u solve the problem. Header path is a headache problem in plugin, I will never know the project directory structure of everyone lol

**Comment by kelset** [comment]
Y you are right, I totally understand you.
Imho you should have really something like a 0.3.6 with "my" header styles and a 0.3.7+ with the RN0.40+ version - but I'm not sure npm allows you to re-upload "old" versions.

**Comment by RobCherry** [comment]
I have created a fork that can be used for older RN versions.

Update your `package.json`.

```javascript
  ...
  "dependencies": {
    "react-native-textinput-utils": "git@github.com:RobCherry/react-native-textinput-utils#28cdb0b9127e19b227c93994635660f1d7f3b142",
  },
  ...
```
