### ISSUE TITLE
Does NOT work on latest recent React-native [>= 0.47.X]

### ISSUE THREAD

**Issue by kelvin-dev** [DickyT/react-native-textinput-utils#24]
Hi there,
we love your work, keep it up, below is the log we recorded, hopefully its useful for you.
Tons of thanks
![image](https://user-images.githubusercontent.com/19224355/30037652-3a1ba976-91e7-11e7-87fb-86a43b80000b.png)

**Comment by thierryfornetti** [comment]
@DaveAdams88 thanks for your fix, but it doesn't work on React Native 0.48.4.
```
node_modules/react-native-textinput-utils/RCTTextInputUtils/RCTKeyboardToolbar.m:143:42: 
Property access is using 'setSelectedTextRange:' method which is unavailable
```
It appears that `setSelectedTextRange` changed with [this commit](https://github.com/facebook/react-native/commit/a50c9c8e222c6bf792d0d8ae47ef37fffb7da9d1), it probably doesn't work for RN >= 0.48.0.

I think you can solve it by using the [other method](https://github.com/facebook/react-native/blob/19a9c5e41da0aa6ee28a54772edcb92daa498561/Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h#L33), which only needs the variable `notifyDelegate`. Can you check it?
