### ISSUE TITLE
Error with RN 0.27

### ISSUE THREAD

**Issue by williambout** [DickyT/react-native-textinput-utils#5]
`keyboardToolbarDidTouchOnCancel` is not a supported event type for RCTKeyboardObserver

-[RCTEventEmitter addListener:] + 192
    RCTEventEmitter.m @ 65:0
**invoking_** + 140
-[NSInvocation invoke] + 286
-[NSInvocation invokeWithTarget:] + 54
-[RCTModuleMethod invokeWithBridge:module:arguments:] + 1887
-[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 680
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.447 + 1274
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_queue_drain + 2215
_dispatch_queue_invoke + 601
_dispatch_client_callout + 8
_dispatch_root_queue_drain + 1829
_dispatch_worker_thread3 + 111
_pthread_wqthread + 1129
start_wqthread + 13

**Comment by williambout** [comment]
Update : React Native 0.27 is out

**Comment by DickyT** [comment]
I just install 0.27rc everything seems fine. I'll try to downgrade and see what happened to 0.27

**Comment by williambout** [comment]
@DickyT Have you tried with the latest release (0.27.2) ?

**Comment by liujinjun** [comment]
@williambout Did you solve the problem?
0.26 update to 0.28 error 
keyboardToolbarDidTouchOnCancel is not a supported event type for RCTKeyboardObserver

**Comment by DickyT** [comment]
latest version fixed
